config/routes.rb
Rails.application.routes.draw do

  get '/install-instructions', to: 'steps#install_instructions'
  get '/getting-started', to: 'steps#getting_started'
  get '/add-project-to-git', to: 'steps#add_project_to_git'
  get '/running-application', to: 'steps#running_application'
  get '/creating-migration', to: 'steps#creating_migration'
  get '/rails-architecture', to: 'steps#rails_architecture'
  get '/crud-scaffolding', to: 'steps#crud_scaffolding'
  get '/setting-default-page', to: 'steps#setting_default_page'
  get '/deploying-to-heroku', to: 'steps#deploying_to_heroku'
  get '/voting-topics', to: 'steps#voting_topics'
  get '/votes-topics-association', to: 'steps#votes_topics_association'
  get '/allow-people-to-vote', to: 'steps#allow_people_to_vote'
  get '/redirect-topics-after-create', to: 'steps#redirect_topics_after_create'
  get '/topic-title-link', to: 'steps#topic_title_link'
  get '/clean-up-links', to: 'steps#clean_up_links'
  get '/credits', to: 'steps#credits'

  root to: 'steps#overview'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <!--
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    -->
      <a class="navbar-brand" href="/">Introduction to Rails</a>
    </div>
    <!--
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Dashboard</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Help</a></li>
      </ul>
    </div> -->
  </div>
</div>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-sidebar">
  <li class="<%= 'active' if current_page?('/') %>">
    <%= link_to 'Overview', root_path %>
  </li>
  <li class="<%= 'active' if current_page?('/getting-started') %>">
    <%= link_to 'Getting Started', getting_started_path %>
  </li>
  <li class="<%= 'active' if current_page?('/add-project-to-git') %>">
    <%= link_to 'Add The Project To A Git Repo', add_project_to_git_path %>
  </li>
  <li class="<%= 'active' if current_page?('/running-application') %>">
    <%= link_to 'Running Your Application Locally', running_application_path %>
  </li>
  <li class="<%= 'active' if current_page?('/creating-migration') %>">
    <%= link_to 'Creating A Migration', creating_migration_path %>
  </li>
  <li class="<%= 'active' if current_page?('/rails-architecture') %>">
    <%= link_to 'Rails Architecture', rails_architecture_path %>
  </li>
  <li class="<%= 'active' if current_page?('/crud-scaffolding') %>">
    <%= link_to 'CRUD With Scaffolding', crud_scaffolding_path %>
  </li>
  <li class="<%= 'active' if current_page?('/setting-default-page') %>">
    <%= link_to 'Setting The Default Page', setting_default_page_path %>
  </li>
  <li class="<%= 'active' if current_page?('/deploying-to-heroku') %>">
    <%= link_to 'Deploying to Heroku', deploying_to_heroku_path %>
  </li>
  <li class="<%= 'active' if current_page?('/voting-topics') %>">
    <%= link_to 'Voting On Topics', voting_topics_path %>
  </li>
  <li class="<%= 'active' if current_page?('/votes-topics-association') %>">
    <%= link_to 'Hooking Up Votes And Topics', votes_topics_association_path %>
  </li>
  <li class="<%= 'active' if current_page?('/allow-people-to-vote') %>">
    <%= link_to 'Allow People To Vote', allow_people_to_vote_path %>
  </li>
  <li class="<%= 'active' if current_page?('/redirect-topics-after-create') %>">
    <%= link_to 'Redirect To The Topics List After Creating A New Topic', redirect_topics_after_create_path %>
  </li>
  <li class="<%= 'active' if current_page?('/topic-title-link') %>">
    <%= link_to 'Make The Topic Title A Link', topic_title_link_path %>
  </li>
  <li class="<%= 'active' if current_page?('/clean-up-links') %>">
    <%= link_to 'Clean Up Links On The Topics List', clean_up_links_path %>
  </li>
  <li class="<%= 'active' if current_page?('/credits') %>">
    <%= link_to 'Credits And Next Steps', credits_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Introduction To Rails</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <%= render 'layouts/navigation' %>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/steps/add_project_to_git.html.erb
<h1 class="page-header">Add The Project To A Git Repo</h1>
<div class="doc">
  <div class="goals">
    <h1>Goals</h1>
    <ul>
      <li>
        <div class="message">
          <p>Create a local git repository</p>
        </div>
      </li>
      <li>
        <div class="message">
          <p>Add all our files to the git repository</p>
        </div>
      </li>
      <div class="message">
        <p>In order to publish our application, we need to add our application and any changes we make over time to a "revision control system". In our case we're going to use <em>git</em> because it is (relatively) easy and it is what our app server, <em>Heroku</em>, uses.</p>
      </div>
    </ul>
  </div>
  <div class="steps">
    <div class="step">
      <h1>Step 1</h1>
      <blockquote>
        <div class="console">
          <span>Type this in the terminal:</span><pre>git init</pre>
        </div>
        <div class="message">
          <p>It doesn't look like anything really happened, but 'git init' initialized its repository (repo) in a hidden directory called <code>.git</code>. You can see this by typing <code>ls -a</code> (list all files).</p>
        </div>
      </blockquote>
    </div>
    <div class="step">
      <h1>Step 2</h1>
      <blockquote>
        <div class="console">
          <span>Type this in the terminal:</span><pre>git status</pre>
        </div>
        <div class="message">
          <p><code>git status</code> tells you everything git sees as modified, new, or missing.</p>
        </div>
        <div class="message">
          <p>The first time you run this, you should see a ton of stuff.</p>
        </div>
        <div class="message">
          <p>The second time you run this, you shouldn't see much of anything.</p>
        </div>
      </blockquote>
    </div>
    <div class="step">
      <h1>Step 3</h1>
      <blockquote>
        <div class="console">
          <span>Type this in the terminal:</span><pre>git add .</pre>
        </div>
        <div class="message">
          <p><code>git add .</code> tells git that you want to add the current directory (aka <code>.</code>) and everything under it to the repo.</p>
        </div>
        <br />
        <div class="alert alert-info">
          <h3>
            <i class="fa fa-info-circle fa-2x"></i>
            git add
          </h3>
          <div class="message">
            <p>With Git, there are usually many ways to do very similar things.</p>

            <ul>
              <li>
                <code>git add foo.txt</code> adds a file named <code>foo.txt</code>
              </li>
              <li>
                <code>git add .</code> adds all new files and changed files, but <em>keeps</em> files that you've deleted
              </li>
              <li>
                <code>git add -A</code> adds everything, including deletions
              </li>
            </ul>
            <p>"Adding deletions" may sound weird, but if you think of a version control system as keeping
              track of <em>changes</em>, it might make more sense. Most people use <code>git add .</code> but <code>git add -A</code>
              can be safer. No matter what, <code>git status</code> is your friend.</p>
            </div>
          </div>
        </div>
      </blockquote>
    </div>
    <div class="step">
      <h1>Step 4</h1>
      <blockquote>
        <div class="console">
          <span>Type this in the terminal:</span><pre>git commit -m "Initial commit"</pre>
        </div>
        <div class="message">
          <p><code>git commit</code> tells git to actually <em>do</em> all things you've said you wanted to do.</p>
        </div>
        <div class="message">
          <p>This is done in two steps so you can group multiple changes together.</p>
        </div>
        <div class="message">
          <p><code>-m "Initial commit"</code>  is just a shortcut to say what your commit message is. You can skip that part and git will bring up an editor to fill out a more detailed message.</p>
        </div>
      </blockquote>
    </div>
  </div>
  <div class="explanation">
    <h1>Explanation</h1>
    <blockquote>
      <div class="message">
        <p>By checking your application into git now, you're creating a record of your starting point. Whenever you make a change during today's workshop, we'll add it to git before moving on. This way, if anything ever breaks, or you make a change you don't like, you can use git as an all-powerful "undo" technique. But that only works when you remember to commit early and often!</p>
      </div>
    </blockquote>
  </div>
</div>

app/views/steps/allow_people_to_vote.html.erb
<h1 class="page-header">Allow People To Vote</h1>
<div class="doc">
  <div class="goals">
    <h2>Goals</h2>
    <ul>
      <div class="message">
        <p>Now we're going to add a button people can click to cast a vote.</p>
      </div>
    </ul>
  </div>
  <div class="steps">
    <div class="step" title="Add a new controller action for voting">
      <h3>Step 1: Add a new controller action for voting</h3>
      <blockquote>
        <div class="message">
          <p>Edit <code>app/controllers/topics_controller.rb</code> to add a method like this:</p>
        </div>
        <pre class="CodeRay">
def upvote
  @topic = Topic.find(params[:id])
  @topic.votes.create
  redirect_to(topics_path)
end
        </pre>
        <div class="message">
          <ul>
            <li>
              <code>@topic = Topic.find(params[:id])</code> finds the topic in the database with that id and stores it in the variable <code>@topic</code>.
            </li>
            <li>
              <code>@topic.votes.create</code> creates a new vote for the current topic and saves it in the database.
            </li>
            <li>
              <code>redirect_to(topics_path)</code> tells the browser to go back to topics_path (the topics list).
            </li>
          </ul>
        </div>
      </blockquote>
    </div>
    <div class="step" title="Add a new route for voting">
      <h3>Step 2: Add a new route for voting</h3>
      <blockquote>
        <div class="message">
          <p>Open <code>config/routes.rb</code> and find the section that looks like this:</p>
        </div>
        <pre class="CodeRay">resources :topics</pre>
        <div class="message">
          <p>Replace that line so it looks like this:</p>
        </div>
        <pre class="CodeRay">
resources :topics do
  member do
    post 'upvote'
  end
end
        </pre>
        <div class="message">
          <p>Verify that route route was added successfully by checking the output of <code>rake routes</code> or <a href="http://localhost:3000/rails/info">http://localhost:3000/rails/info</a>. You should see a line that looks like this:</p>
          <pre class="CodeRay">
Prefix        Verb   URI Pattern                  Controller#Action
upvote_topic  POST   /topics/:id/upvote(.:format) topics#upvote
          </pre>
        </div>
      </blockquote>
    </div>
    <div class="step" title="Add the button to the view">
      <h3>Step 3: Add the button to the view</h3>
      <blockquote>
        <div class="message">
          <p>Edit <code>app/views/topics/index.html.erb</code> so that the bottom loop looks like this:</p>
        </div>
        <pre class="CodeRay">
<span class="inline"><span class="inline-delimiter">&lt;%</span> <span class="instance-variable">@topics</span>.each <span class="keyword">do</span> |topic| <span class="inline-delimiter">%&gt;</span></span>
  <span class="tag">&lt;tr&gt;</span>
    <span class="tag">&lt;td&gt;</span><span class="inline"><span class="inline-delimiter">&lt;%=</span> topic.title <span class="inline-delimiter">%&gt;</span></span><span class="tag">&lt;/td&gt;</span>
    <span class="tag">&lt;td&gt;</span><span class="inline"><span class="inline-delimiter">&lt;%=</span> topic.description <span class="inline-delimiter">%&gt;</span></span><span class="tag">&lt;/td&gt;</span>
    <span class="tag">&lt;td&gt;</span><span class="inline"><span class="inline-delimiter">&lt;%=</span> pluralize(topic.votes.count, <span class="string"><span class="delimiter">"</span><span class="content">vote</span><span class="delimiter">"</span></span>) <span class="inline-delimiter">%&gt;</span></span><span class="tag">&lt;/td&gt;</span>
    <span class="tag">&lt;td&gt;</span><span class="inline"><span class="inline-delimiter">&lt;%=</span> button_to <span class="string"><span class="delimiter">'</span><span class="content">+1</span><span class="delimiter">'</span></span>, upvote_topic_path(topic), <span class="key">method</span>: <span class="symbol">:post</span> <span class="inline-delimiter">%&gt;</span></span><span class="tag">&lt;/td&gt;</span>
    <span class="tag">&lt;td&gt;</span><span class="inline"><span class="inline-delimiter">&lt;%=</span> link_to <span class="string"><span class="delimiter">'</span><span class="content">Show</span><span class="delimiter">'</span></span>, topic <span class="inline-delimiter">%&gt;</span></span><span class="tag">&lt;/td&gt;</span>
    <span class="tag">&lt;td&gt;</span><span class="inline"><span class="inline-delimiter">&lt;%=</span> link_to <span class="string"><span class="delimiter">'</span><span class="content">Edit</span><span class="delimiter">'</span></span>, edit_topic_path(topic) <span class="inline-delimiter">%&gt;</span></span><span class="tag">&lt;/td&gt;</span>
    <span class="tag">&lt;td&gt;</span><span class="inline"><span class="inline-delimiter">&lt;%=</span> link_to <span class="string"><span class="delimiter">'</span><span class="content">Destroy</span><span class="delimiter">'</span></span>, topic, <span class="key">method</span>: <span class="symbol">:delete</span>, <span class="key">data</span>: { <span class="key">confirm</span>: <span class="string"><span class="delimiter">'</span><span class="content">Are you sure?</span><span class="delimiter">'</span></span> } <span class="inline-delimiter">%&gt;</span></span><span class="tag">&lt;/td&gt;</span>
  <span class="tag">&lt;/tr&gt;</span>
<span class="inline"><span class="inline-delimiter">&lt;%</span> <span class="keyword">end</span> <span class="inline-delimiter">%&gt;</span></span>
        </pre>
        <div class="message">
          <ul>
            <li>
              <code>pluralize(topic.votes.count, "vote")</code> displays the number of votes the topic has, plus the word 'vote' or 'votes' accordingly.
            </li>
            <li>
              <code>button_to '+1'</code> creates an html button with the text '+1'.
            </li>
            <li>
              <code>topic_upvote_path(topic)</code> creates the appropriate URL for the action we want to invoke. In this case, we want to upvote the current topic.

              <ul>
                <li>
                  <code>topic_upvote_path(topic)</code> would return <code>/topics/42/upvote</code> (if topic.id was 42)
                </li>
              </ul>
            </li>
            <li>
              <code>method: :post</code> ensures we do the create action of CRUD, not the read action.
            </li>
          </ul>
        </div>
      </blockquote>
    </div>
    <div class="step" title="Confirm your changes in the browser">
      <h3>Step 4: Confirm your changes in the browser</h3>
      <blockquote>
        <div class="message">
          <p>Go back to <a href="http://localhost:3000/topics">http://localhost:3000/topics</a> and play.</p>
        </div>
        <div class="message">
          <p>Revel in the fact that you didn't have to restart the server to see these changes. Hawt, no?</p>
        </div>
      </blockquote>
    </div>
  </div>
</div>

app/views/steps/clean_up_links.html.erb
<h1 class="page-header">Clean Up Links On The Topics List</h1>
<div class="doc">
  <div class="goals">
    <h2>Goals</h2>
    <div class="message">
      <p>Our app is nearly done! The main topics listing page is pretty busy. There are a lot of links that aren't necessary.</p>
    </div>
    <div class="message">
      <p>Let's clean up the topics list page by doing the following:</p>
    </div>
    <ul>
      <li><div class="message">
        <p>Remove the 'show' link</p>
      </div></li>
      <li><div class="message">
        <p>Remove the 'edit' link</p>
      </div></li>
      <li><div class="message">
        <p>Change 'destroy' to 'delete'</p>
      </div></li>
    </ul>
  </div>
  <div class="steps">
    <div class="step" title="Remove the 'show' and 'edit' links">
      <h3>Step 1: Remove the 'show' and 'edit' links</h3>
      <blockquote>
        <div class="message">
          <p>Open <code>app/views/topics/index.html.erb</code> and remove these two lines:</p>
        </div>
        <pre class="CodeRay">
<span class="tag">&lt;td&gt;</span><span class="inline"><span class="inline-delimiter">&lt;%=</span> link_to <span class="string"><span class="delimiter">'</span><span class="content">Show</span><span class="delimiter">'</span></span>, topic <span class="inline-delimiter">%&gt;</span></span><span class="tag">&lt;/td&gt;</span>
<span class="tag">&lt;td&gt;</span><span class="inline"><span class="inline-delimiter">&lt;%=</span> link_to <span class="string"><span class="delimiter">'</span><span class="content">Edit</span><span class="delimiter">'</span></span>, edit_topic_path(topic) <span class="inline-delimiter">%&gt;</span></span><span class="tag">&lt;/td&gt;</span></pre>
      </blockquote>
    </div>
    <div class="step" title="Change 'destroy' to 'delete'">
      <h3>Step 2: Change 'destroy' to 'delete'</h3>
      <blockquote>
        <div class="message">
          <p>Change the line with the word 'Destroy' to this:</p>
        </div>
        <pre class="CodeRay"><span class="tag">&lt;td&gt;</span><span class="inline"><span class="inline-delimiter">&lt;%=</span> link_to <span class="string"><span class="delimiter">'</span><span class="content">Delete</span><span class="delimiter">'</span></span>, topic, <span class="key">method</span>: <span class="symbol">:delete</span>, <span class="key">data</span>: { <span class="key">confirm</span>: <span class="string"><span class="delimiter">'</span><span class="content">Are you sure?</span><span class="delimiter">'</span></span> } <span class="inline-delimiter">%&gt;</span></span><span class="tag">&lt;/td&gt;</span></pre>
      </blockquote>
    </div>
    <div class="step" title="Confirm your changes">
      <h3>Step 3: Confirm your changes</h3>
      <blockquote>
        <div class="message">
          <p>Now save your file and try reloading in your browser to see the changes.</p>
        </div>
      </blockquote>
    </div>
  </div>
  <div class="explanation">
    <h2>Explanation</h2>
    <blockquote><div class="message"><ul>
      <li><p>The two links we removed were show and edit.  We did this because the title now links to the show page and from the show page you can reach the edit page.</p></li>
      <li><p>The second change we made was to make the link text 'Delete' instead of destroy.</p></li>
    </ul></div></blockquote>
  </div>
</div>

app/views/steps/creating_migration.html.erb
<h1 class="page-header">Creating A Migration</h1>
<div class="doc">
  <div class="goals">
    <h1>Goals</h1>
    <ul>
      <table class="table table-bordered">
        <thead><tr><th>Topics</th></tr></thead>
        <tbody>
          <tr><td>id</td></tr>
          <tr><td>title</td></tr>
          <tr><td>description</td></tr>
        </tbody>
      </table>
      <div class="message">
        <p>The suggestotron has a list of topics that people can vote on. We'll store our topics in the database. In this step you'll do the following:</p>
      </div>
      <li>
        <div class="message">
          <p>Create a a simple <em>Table</em> in the database for topics with a title and a description</p>
        </div>
      </li>
      <li>
        <div class="message">
          <p>Automatically generate the corresponding <em>Scaffold</em> in Rails (namely, the <em>Model</em>, the <em>View</em>, and the <em>Controller</em>).</p>
        </div>
      </li>
    </ul>
  </div>
  <div class="steps">
    <div class="step">
      <h1>Step 1</h1>
      <blockquote>
        <div class="console">
          <span>Type this in the terminal:</span><pre>rails generate scaffold topic title:string description:text</pre>
        </div>
        <div class="message">
          <ul>
            <li>
              <code>generate scaffold</code> tells rails to create everything necessary to get up and running with topics.
            </li>
            <li>
              <code>topic</code> tells rails the name of the new model.
            </li>
            <li>
              <code>title:string</code> says that topics have a title, which is a "string".
            </li>
            <li>
              <code>description:text</code> says that topics have a description which is a "text". (What's the difference between "string" and "text"? Basically "text" is for strings that might be very long.)
            </li>
          </ul>
        </div>
      </blockquote>
    </div>
    <div class="step">
      <h1>Step 2</h1>
      <blockquote>
        <div class="console">
          <span>Type this in the terminal:</span><pre>rake db:migrate</pre>
        </div>
        <div class="message">
          <p>This tells rails to update the database to include a table for our new model.</p>
        </div>
      </blockquote>
    </div>
  </div>
  <div class="explanation">
    <h1>Explanation</h1>
    <blockquote>
      <h2>Rake</h2>
      <div class="message">
        <p><code>rake</code> <em>(ruby make)</em> is a tool that allows you to run small Ruby programs (<strong>tasks</strong>) that you use often in your application.</p>

        <p>Here, <code>rake db:migrate</code> is a task provided by the Rails framework. It creates a bunch of new files, including a <em>migration</em>, a <em>model</em>, a <em>view</em>, and a <em>controller</em>.</p>
      </div>
      <div class="alert alert-info">
        <h5>
          <i class="fa fa-info-circle fa-2x"></i>
          You can run <code>rake -T</code> to see a list of all the <code>rake</code> commands your app currently responds to, along with a short description of each task.
        </h5>
      </div>
    </div>
  </blockquote>
</div>
</div>

app/views/steps/credits.html.erb
<h1 class="page-header">Credits And Next Steps</h1>
<div class="doc">
  <div class="message">
    <p>Guess what?  <em><strong>You're done!!!</strong></em> Congratulations, you just "finished" your first rails app!</p>

    <p>(They're never <em>really</em> ever finished... have fun tweaking it!)</p>

    <h2>Extra Credit</h2>

    <p>If you got all the way through Suggestotron with some time to spare, here's some extra stuff you can try:</p>

    <ul>
      <li>Add a downvote button that does the opposite of what the upvote button does</li>
      <li>Sort topics by their number of votes</li>
      <li>Add an 'about' page, linked from the bottom of the Suggestotron topics list. Link back to the Topics list from the About page so users don't get stranded.</li>
      <li>
        If your class has a <strong>lot</strong> of time left over:
        <ul>
          <li>Users should be allowed to vote only once: give votes a user_id and allow a user to have voted on each topic only once. But wait, what is a 'user' in our system? Get a volunteer to introduce everyone to <a href="https://github.com/plataformatec/devise">Devise</a>, a simple way to add authentication to a Rails application.</li>
          <li>Users should be able to give a post a 'negative' vote instead of a positive one. How might you represent that in this system?</li>
        </ul>
      </li>
    </ul>
  </div>
  <h1>Authors</h1>
  <ul>
    <li>Sarah Allen</li>
    <li>Sarah Mei</li>
    <li>Alex Chaffee</li>
    <li>Ryan Davis</li>
    <li>Steven! Ragnarok</li>
    <li>...and many, many others</li>
  </ul>
  <h1>What next?</h1>
  <ul>
    <li>Probably time for the closing presentation.</li>
    <li>After that, start a project, tutorial, and come back again!</li>
    <li>
      <span>All our favorite resources can be found on the RailsBridge site: </span>
      <a href="http://railsbridge.org/learn/resources">http://railsbridge.org/learn/resources</a>
    </li>
  </ul>
</div>

app/views/steps/getting_started.html.erb
<h1 class="page-header">Getting Started</h1>
<div class="doc">
  <%= image_tag 'Start_page.png', alt: '' %>
  <div class="goals">
    <h1>Goals</h1>
    <ul>
      <li>
        <div class="message">
          <p>Create Your New Application</p>
        </div>
      </li>
      <div class="message">
        <p>Let's get started! By the end of this step, we'll have a brand-spankin'-new (empty) rails app.</p>
      </div>
    </ul>
  </div>
  <div class="steps">
    <h1>Steps</h1>
    <div class="alert alert-info">
      <h3>
        <i class="fa fa-info-circle fa-2x"></i>
        Don't hesitate to ask questions if you have <em>any</em> problems!
      </h3>
    </div>
    <h1>Step 1</h1>
    <blockquote>
      <div class="console">
        <span>Type this in the terminal where you want to create your new rails application:</span><pre>rails new suggestotron -m https://gist.githubusercontent.com/mathieugagne/11214649/raw/c22dfbe6bc628fc9222a91ac1ca68180fb3f368e/suggestotron.rb</pre>
      </div>
      <div class="message">
        <p><code>rails new</code> creates a new rails project with the name you give.</p>
      </div>
      <div class="message">
        <p>In this case we told it to create a new project called <code>suggestotron</code>. We'll go into detail on what it created shortly.</p>
      </div>
    </blockquote>
  </div>
  <div class="step">
    <h1>Step 2</h1>
    <blockquote>
      <div class="console">
        <span>Type this in the terminal:</span><pre>cd suggestotron</pre>
      </div>
      <div class="message">
        <p>'cd' stands for change directory.</p>
      </div>
      <div class="message">
        <p>'cd suggestotron' makes suggestotron our current directory.</p>
      </div>
    </blockquote>
  </div>
  <div class="step">
    <h1>Step 3</h1>
    <blockquote>
      <div class="console">
        <span>Type this in the terminal:</span><pre>ls</pre>
      </div>
      <div class="message">
        <p>'ls' stands for 'list (stuff)'.</p>
      </div>
      <div class="message">
        <p>It shows you the contents of the current folder.</p>
      </div>
    </blockquote>
  </div>
  <div class="step">
    <h1>Step 4</h1>
    <blockquote>
      <div class="message">
        <p>Open the suggestotron folder as a project in your text editor.</p>

        <p>In <strong>Sublime Text 2</strong>, you can use the <code>Project &gt; Add Folder to Project...</code> menu option:</p>

        <p><%= image_tag "sublime_add_folder_to_project.png", alt: '' %></p>

        <p>Select your <code>suggestotron</code> folder from the file picker that opens. If everything works out Sublime should look something like this:</p>

        <p><%= image_tag "sublime_project_as_folder.png", alt: '' %></p>
      </div>
    </blockquote>
    </div>
    <div class="message">
      <p>You can see that <code>rails new</code> created a lot directories and
        files. The ones we want to focus on today are:</p>
      </div>
      <table class='table'>
        <tbody><tr>
          <th>File/Folder</th>
          <th>Purpose</th>
        </tr>
        <tr>
          <td>app/</td>
          <td>Contains the controllers, models, and views for your application.  You will do most of your work here.</td>
        </tr>
        <tr>
          <td>config/</td>
          <td>Configure your application's runtime rules, routes, database, and more.</td>
        </tr>
        <tr>
          <td>db/</td>
          <td>Shows your current database schema, as well as the database migrations.</td>
        </tr>
        <tr>
          <td>public/</td>
          <td>The only folder seen to the world as-is. If you put files in here, they will be served directly without any processing by Rails.</td>
        </tr>
        <tr>
          <td>app/assets/</td>
          <td>This is where your images, JavaScript, stylesheets (CSS), and other static files should go. Modern rails apps use something called the Assets Pipeline, which combines all the JavaScript and CSS files in this directory into a single file for speediness.</td>
        </tr>
      </tbody></table>
      <div class="message">
        <p>There is a lot more that <code>rails new</code> created. Probably enough to fill a book, so we're going to ignore them for now.</p>
      </div>
    </blockquote>
  </div>
</div>